[package]
name = "recon"
version = "0.1.0"
authors = ["Chris Dawes <cmsd2@cantab.net>"]
license = "Apache-2.0"

[lib]

[dependencies]
recon-link = { version = "0.3.1-alpha.0", path = "../recon-link" }
